# Generated by Django 5.2.8 on 2026-01-26 15:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('rating', models.FloatField()),
                ('cuisine_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('max_discount', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='restaurants_api_app.restaurants')),
            ],
        ),
    ]
